version: '3.8'
services:
  paymentservice:
    build:
      context: ./payment
      dockerfile: Dockerfile
    ports:
      - 9090:9090

  supportservice:
    build:
      context: ./support
      dockerfile: Dockerfile
  ports:
    - 8080:8080